laba_10_API/config/routes.rb
Rails.application.routes.draw do
  root 'sequence#input'

  get 'sequence/input'
  get 'sequence/view'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

laba_10_API/app/controllers/sequence_controller.rb
# frozen_string_literal: true

# Контроллер для последовательности
class SequenceController < ApplicationController
    def input
    end
  
    def view
      @input = validate_input params[:values]
      subs_arr = find_increasing_subs.filter { |arr| arr.count > 1 }
      @subs = subs_arr.map { |subseq| subseq.join(' ') }
      @result = subs_arr.max_by(&:length).join(' ')
      @input = @input.join(' ')
    rescue StandardError => e
      @error = case e.class.to_s
               when 'ArgumentError' then 'Введены посторонние символы'
               when 'NoMethodError' then 'Последовательность не найдена'
               else e
               end
    end
    
  
    private
  
    def find_increasing_subs
      @input.each_with_object([[]]) do |el, acc|
        acc << [] if acc[-1].any? && el <= acc[-1][-1]
        acc[-1] << el
      end
    end
  
    def validate_input(input)
      raise 'Ошибочный GET-запрос' if input.nil?
      raise 'Вы ничего не ввели' if input.empty?
  
      result = input.split.map { |el| Integer el }
      raise 'Последовательность короче 10 чисел' if result.length < 10
  
      result
    end
  end
  

laba_10_API/app/helpers/palindrome_helper.rb
module PalindromeHelper
end

laba_10_API/app/helpers/sequence_helper.rb
module SequenceHelper
end

laba_10_API/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Laba10Api</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

laba_10_API/app/views/sequence/input.html.erb
<h1 class="m-3">Поиск последовательности</h1>
<p class="m-3 text-truncate">Будет определена наиболее длинная монотонно возрастающая последовательность чисел.</p>
<div class="w-50">
    <%= form_tag sequence_view_path, method: 'get', class: 'm-3' do %>
            <div class="col-12"><%= label_tag :values, 'Введите последовательность чисел через пробел:' %></div>
            <div class="row mt-2">
                <div class="col-11 p-1 m-0"><%= text_field_tag :values, '', class: 'form-control', required: true %></div>
                <div class="col-1 p-1 m-0"><%= button_tag "Найти", type: 'submit', name: nil, class: 'btn btn-primary' %></div>
            </div>
    <% end %>
</div>

laba_10_API/app/views/sequence/view.html.erb
<h1 class="m-3">Результат поиска</h1>

<% if @error %>
    <p class="text-danger m-3"><%= @error %></p>
<% else %>

<div class="m-3">Вы ввели: <%= @input %></div>
<div class="w-25 m-3 table-responsive">
    <table class="table table-striped table-sm table-bordered">
        <thead class="text-center">
            <tr>
                <th scope="col">No.</th>
                <th scope="col">Последовательность</th>
            </tr>
        </thead>
        <tbody>
            <% @subs.each.with_index(1) do |subseq, ind| %>
                <tr>
                    <th scope="row" class="col-1 text-center"><%= ind %></th>
                    <td><%= subseq %></td>
                </tr>
            <% end %>
            <tr>
                    <th scope="row" class="col-1 text-center">Ответ</th>
                    <td><%= @result %></td>
                </tr>
        <tbody>
    </table>
</div>
<% end %>
<br>
<button type="button" class="btn btn-link">
    <%= link_to 'Домой', root_path %>
</button>

laba_10_API/app/views/sequence/view.xml.erb
<?xml version="1.0" encoding="UTF-8"?> 
<output>
<% if @error %>
    <error><%= @error %></error>
<% else %>
<input><%= @input %></input>

<calculations>
    <% @subs.each.with_index(1) do |subseq, ind| %>
    <sequence data-index="<%= ind %>"><%= subseq %></sequence>
    <% end %>
</calculations>
<answer>
    <sequence><%= @result %></sequence>
</answer>
<% end %>
</output>