laba_10_Proxy/config/routes.rb
Rails.application.routes.draw do
  root 'negotiator#input'

  get 'negotiator/input'
  get 'negotiator/view'
  get 'negotiator/rawview'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

laba_10_Proxy/app/controllers/negotiator_controller.rb
# frozen_string_literal: true

require 'net/http'
require 'nokogiri'

# Класс контроллера-посредника
class NegotiatorController < ApplicationController
  BASE_API_URL           = 'http://localhost:3000/sequence/view'
  XSLT_BROWSER_TRANSFORM = '/browser_transform.xslt'
  XSLT_SERVER_TRANSFORM  = "#{Rails.root}/public/server_transform.xslt"

  def input
  end

  def view
    responce = make_query BASE_API_URL
    respond_to do |format|
      format.html do
        @output = xslt_transform(responce).to_html
        render 'view'
      end
      format.xml { render xml: insert_browser_xslt(responce).to_xml }
      format.rss { render xml: insert_browser_xslt(responce).to_xml }
    end
  end

  def rawview
  if @input.present?
    uri = URI(BASE_API_URL + ".xml?values=#{@input}")
    response = Net::HTTP.get_response(uri)
    if response.is_a?(Net::HTTPSuccess)
      render xml: response.body
    else
      render plain: 'Error while fetching data from API', status: :internal_server_error
    end
  else
    render xml: '<output><error>Вы ничего не ввели</error></output>'
  end
end

  private

  def make_query(server_url)
    query_str = "#{server_url}.xml"
    query_str << "?values=#{@input}" if (@input = params[:values]&.split(' ')&.join('+'))
    HTTP.get(query_str).body
  end

  def xslt_transform(data, transform: XSLT_SERVER_TRANSFORM)
    doc = Nokogiri::XML(data)
    xslt = Nokogiri::XSLT(File.read(transform))
    xslt.transform(doc)
  end

  # Чтобы преобразование XSLT на клиенте работало, надо вставить ссылку на XSLT.
  # Делается это с помощью nokogiri через ProcessingInstruction (потому что ссылка
  # на XSLT называется в XML processing instruction).
  def insert_browser_xslt(data, transform: XSLT_BROWSER_TRANSFORM)
    doc = Nokogiri::XML(data)
    xslt = Nokogiri::XML::ProcessingInstruction.new(doc,
                                                    'xml-stylesheet',
                                                    'type="text/xsl" href="' + transform + '"')
    doc.root.add_previous_sibling(xslt)
    # Возвращаем doc, так как предыдущая операция возвращает не XML-документ.
    doc
  end
end

laba_10_Proxy/app/helpers/negotiator_helper.rb
module NegotiatorHelper
end

laba_10_Proxy/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Laba10Proxy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

laba_10_Proxy/app/views/negotiator/input.html.erb
<h1 class="m-3">Поиск последовательности</h1>
<p class="m-3">Будет определена наиболее длинная монотонно возрастающая последовательность чисел.</p>
<div class="w-50">
    <%= form_tag nil, method: 'get', class: 'm-3', id: 'input_form' do %>
            <div class="col-12"><%= label_tag :values, 'Введите последовательность чисел через пробел:' %></div>
            <div class="mt-2">
                <div class="p-1 m-0"><%= text_field_tag :values, '', class: 'form-control', required: true %></div>
            </div>
            <div class="mt-2 d-flex justify-content-center">
                <div class="p-1 m-0"><%= button_tag "Получить ответ в HTML", id: 'btn_commit_html', type: 'submit', name: nil, class: 'btn btn-primary', formaction: "#{negotiator_view_path}.html" %></div>
                <div class="p-1 m-0"><%= button_tag "Получить ответ в XML", id: 'btn_commit_xml', type: 'submit', name: nil, class: 'btn btn-primary', formaction: "#{negotiator_view_path}.xml" %></div>
            </div>
    <% end %>
</div>

laba_10_Proxy/app/views/negotiator/view.html.erb
<h1 class="m-3">Результат поиска</h1>

<%== @output %>

<button type="button" class="btn btn-link">
    <%= link_to 'Домой', root_path %>
</button>